<Container>:
    rows: 3
    input: input
    img: img

    AnchorLayout:
        size_hint_y: .2

        TextInput:
            id: input
            multiline: False
            font_size: '25sp'

    AsyncImage:
        id: img

    FloatLayout:
        size_hint_y: .8

        Button:
            text: 'QRcode'
            font_size: '35sp'
            size_hint: .5, .3
            pos_hint: {'center_x': .5, 'center_y': .4}

            on_release:
                root.show_qr()
